name: Test 🧪
on:
  push:
    branches-ignore:
      - master
      - beta
jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - name: 🛑 Cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0
      - name: 📩 Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: ⚙️ Setup node@${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: 📬 Install dependencies
        run: yarn install --frozen-lockfile
      - name: 🧪 Test
        run: |
          echo "UPTIMEROBOT_TEST_API_TOKEN=$UPTIMEROBOT_TEST_API_TOKEN" > .env
          npm run test:ci
        env:
          CI: true
          UPTIMEROBOT_TEST_API_TOKEN: ${{ secrets.UPTIMEROBOT_TEST_API_TOKEN }}
      - name: ☂️ Upload coverage reports to Codecov
        if: matrix.node-version == 16
        uses: codecov/codecov-action@v3
